version: '3.9'
services:
  web:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - ARANGO_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "8000:5000"
    networks:
      - bridge

networks:
  network:
    driver: bridge